name: Mirror Docker Image From gcr.io

on:
  workflow_dispatch:
    inputs:
      name:
        required: true
      platform:
        type: choice
        default: linux/amd64
        options:
        - linux/386
        - linux/amd64
        - linux/arm/v6
        - linux/arm/v7
        - linux/arm64/v8

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Pull Image
        run: docker pull --platform ${{ github.event.inputs.platform }} gcr.io/${{ github.event.inputs.name }}
      - name: Tag and Push Image
        run: |
          name=${{ secrets.DOCKERHUB_USERNAME }}/${${{ github.event.inputs.name }}/\/./}
          docker tag gcr.io/${{ github.event.inputs.name }} $name
          docker push $name
